swagger: '2.0'
info:
  version: 1.0.3
  title: cbs
  description: "本文档内的所有API均使用`状态码200`返回调,所有关于云硬盘大小的单位均为MB"
tags:
  - name: console-controller
    description: Console Controller
consumes:
  - application/json
produces:
  - application/json
paths:
  /cbs/regions:
    get:
      tags:
        - console-controller
      summary: 查看所有区域列表信息
      operationId: getAllRegionInfoUsingGET
      responses:
        '200':
          description: OK
          schema:
           example:
              code: OK
              data:
                - regionId: lf-tst
                  regionName: 廊坊测试
                  regionDomain: 'https://lf-tst.cbs.console.tg.unicom.local'
                - regionId: xx-tst
                  regionName: 西咸测试
                  regionDomain: 'https://xx-tst.cbs.console.tg.unicom.local'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  '/cbs/regions/{regionId}/apps/instances':
    get:
      tags:
        - console-controller
      summary: 其他产品侧获取资源实例列表
      operationId: fetchInstancesByOtherUsingGET
      parameters:
        - name: regionId
          in: path
          description: 区域编码
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            example:
              code: OK
              data:
                - accountId: '694159455418'
                  instanceId: welkin844dbed1.testcreate
                  imageName: testcreate
                  regionId: lf-tst
                  createTime: 1568448479000
                  imageSize: 6144
                  type: capacity
                  userName: leo
                  userId: '694159455418'
                  imageUsedSize: 0
                  poolName: welkin844dbed1
                  status: INITED     
  '/cbs/regions/{regionId}/apps/instance':
    get:
      tags:
        - console-controller
      summary: 其他产品侧通过应用Id获取云硬盘实例id
      operationId: fetchInstanceIdByOtherUsingGET
      parameters:
        - name: regionId
          in: path
          description: 区域编码
          required: true
          type: string
        - name: apdId
          in: query
          description: 使用云硬盘的应用id
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            example:
              code: OK
              data: 
                instanceId: welkinfdsfdfd.test
  '/cbs/regions/{regionId}/actions/{actionCode}/permission':
    get:
      tags:
        - console-controller
      summary: 查看当前操作是否有权限
      operationId: hasPermissionUsingGET
      parameters:
        - name: actionCode
          in: path
          description: 操作编码
          required: true
          type: string
        - name: regionId
          in: path
          description: 区域编码
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            example:
              code: OK
              message: API访问未授权
              data:
                hasPermission: true
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  '/cbs/regions/{regionId}/cbs':
    get:
      tags:
        - console-controller
      summary: 查看当前登录账户的存储服务状态
      operationId: fetchCbsUsingGET
      parameters:
        - name: regionId
          in: path
          description: 区域编码
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            example:
              code: OK
              message: ok
              data:
                - accountId: '694159455418'
                  allocateSize: 0
                  totalSize: 0
                  createTime: 1568441933000
                  type: availability
                  userName: leo
                  keyring: AQBShnxdZHsbDxAAVtzffBQ+2N4QWrcyfbM30w==
                  poolName: welkin6819772b
                - accountId: '694159455418'
                  allocateSize: 0
                  totalSize: 0
                  createTime: 1568441933000
                  type: capacity
                  userName: leo
                  keyring: AQBShnxdZHsbDxAAVtzffBQ+2N4QWrcyfbM30w==
                  poolName: welkindbc63189
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
    post:
      tags:
        - console-controller
      summary: 为当前登录的账户开通存储服务
      operationId: openCbsUsingPOST
      parameters:
        - name: regionId
          in: path
          description: 区域编码
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
              example:
               code: OK
               message: 开通成功
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
    delete:
      tags:
        - console-controller
      summary: 关闭当前登录账户某个区域的存储服务
      operationId: removeCbsUsingDELETE
      parameters:
        - name: regionId
          in: path
          description: 区域编码
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
             example:
              code: OK
              message: 关闭成功
        '204':
          description: No Content
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
  '/cbs/regions/{regionId}/cbsInstances':
    get:
      tags:
        - console-controller
      summary: 查看当前登录账户的特定区域资源实例列表
      operationId: getCbsInstanceUsingGET
      parameters:
        - name: regionId
          in: path
          description: 区域编码
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            example:
              code: OK
              data:
                - accountId: '694159455418'
                  instanceId: welkin844dbed1.testcreate
                  imageName: testcreate
                  regionId: lf-tst
                  createTime: 1568448479000
                  imageSize: 6144
                  type: capacity
                  userName: leo
                  userId: '694159455418'
                  imageUsedSize: 0
                  poolName: welkin844dbed1
                  status: INITED
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
    post:
      tags:
        - console-controller
      summary: 为当前登录账户在特定区域创建资源实例
      operationId: createCbsInstanceUsingPOST
      parameters:
        - name: regionId
          in: path
          description: 区域编码
          required: true
          type: string
        - in: body
          name: rbdImage
          description: rbdImage
          required: true
          schema:
            type: object
            properties:
              imageName:
                type: string
                example: welkinportaltest
                description: 云硬盘名称
              imageSize:
                type: integer
                format: int64
                example: 500
                description: 云硬盘容量
              poolName:
                type: string
                example: welkin1d8c16d7
                description: 存储池
              type:
                type: string
                example: capacity
                description: 云硬盘类型
      responses:
        '200':
          description: OK
          schema:
             example:
              code: OK
              data:
                accountId: '694159455418'
                instanceId: welkin6819772b.test34
                imageName: test34
                regionId: xx-tst
                createTime: 1568604122492
                imageSize: 1024
                type: availability
                userName: leo
                userId: '694159455418'
                imageUsedSize: 0
                poolName: welkin6819772b
                status: INITED
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  '/cbs/regions/{regionId}/cbsInstances/{instanceId}':
    put:
      tags:
        - console-controller
      summary: 云硬盘扩容
      operationId: expandCbsInstanceUsingPUT
      parameters:
        - name: regionId
          in: path
          description: 区域编码
          required: true
          type: string
        - name: instanceId
          in: path
          description: 云硬盘实例id
          required: true
          type: string
        - name: newSize
          in: query
          description: 扩容后大小
          required: true
          type: integer
          format: int32
      responses:
        '200':
          description: OK
          schema:
            example:
              code: OK
              message: 销毁成功
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
    delete:
      tags:
        - console-controller
      summary: 销毁特定的资源实例
      operationId: deleteCbsInstanceUsingDELETE
      parameters:
        - name: regionId
          in: path
          description: 区域编码
          required: true
          type: string
        - name: instanceId
          in: path
          description: 云硬盘实例id
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
             example:
              code: OK
              message: 销毁成功
        '204':
          description: No Content
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
  '/cbs/regions/{regionId}/cbsInstances/{instanceId}/appId':
    put:
      tags:
        - console-controller
      summary: 修改占用云硬盘的appId
      operationId: updateCbsAppIdUsingPUT
      parameters:
        - name: regionId
          in: path
          description: 区域列表
          required: true
          type: string
        - name: instanceId
          in: path
          description: 云硬盘实例id
          required: true
          type: string
        - name: appId
          in: query
          description: 应用id
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            example:
              code: OK
              message: 修改成功
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  '/cbs/regions/{regionId}/cost':
    post:
      tags:
        - console-controller
      summary: 获取不同分区的价格信息
      operationId: getImagePriceUsingPOST
      parameters:
        - name: regionId
          in: path
          description: 区域编码
          required: true
          type: string
        - in: body
          name: body
          description: body
          required: true
          schema:
            type: object
            properties:
              size:
                type: integer
                description: 云硬盘大小
                example: 2048
              type:
                example: capacity
                type: string
                description: 云硬盘类型
      responses:
        '200':
          description: OK
          schema:
            example:
              code: OK
              data:
                cost: 9
                unit: 元/天
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  '/cbs/regions/{regionId}/instances/{imageName}/existence':
    get:
      tags:
        - console-controller
      summary: 判断特定账户是否拥有同名卷
      operationId: hasTheSameRBDUsingGET
      parameters:
        - name: regionId
          in: path
          description: 区域编码
          required: true
          type: string
        - name: imageName
          in: path
          description: 云硬盘名称
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
           example:
              code: OK
              data:
                isExist: false
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found

 
